/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/cherry_blossom.glb 
Author: sheana (https://sketchfab.com/sheana)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cherry-blossom-f794c81a2e104d07b5a58d8269e57b7f
Title: Cherry Blossom
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cherry_blossom.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.cherry_blossom_cherry_blossom_0.geometry} material={materials.cherry_blossom} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/cherry_blossom.glb')
