/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/ice_cream_soda.glb 
Author: horse_water (https://sketchfab.com/keitamamizu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ice-cream-soda-e436e83c202e432bab97560931c8df9a
Title: Ice Cream Soda
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ice_cream_soda.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Glass_Glass_0.geometry} material={materials.Glass} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Soda_Soda_0.geometry} material={materials.Soda} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.IceCream_IceCreamVanilla_0.geometry} material={materials['IceCream.Vanilla']} position={[-2.344, 322.816, 1.269]} rotation={[-1.468, 0.084, 2.454]} scale={53.393} />
        <mesh geometry={nodes.Cherry_Cherry_0.geometry} material={materials.Cherry} position={[44.337, 325.215, -32.749]} rotation={[-2.15, -0.268, -0.533]} scale={84.972} />
        <mesh geometry={nodes.Straw_Straw_0.geometry} material={materials.Straw} position={[-9.462, 68.945, 5.619]} rotation={[-1.509, 0.24, -1.886]} scale={100} />
        <mesh geometry={nodes.Bubbles_Bubble_0.geometry} material={materials.Bubble} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Ice001_Ice_0.geometry} material={materials.material} position={[-24.888, 289.766, -18.712]} rotation={[-1.625, 0.51, 0.11]} scale={91.637} />
        <mesh geometry={nodes.Ice002_Ice_0.geometry} material={materials.material} position={[36.432, 289.766, -1.634]} rotation={[-1.28, -0.125, -0.519]} scale={71.156} />
        <mesh geometry={nodes.Ice003_Ice_0.geometry} material={materials.material} position={[17.595, 294.356, -29.479]} rotation={[-1.776, -0.356, -2.295]} scale={72.305} />
        <mesh geometry={nodes.Ice004_Ice_0.geometry} material={materials.material} position={[8.277, 294.356, 16.478]} rotation={[-1.088, -0.184, -1.065]} scale={77.093} />
        <mesh geometry={nodes.Ice005_Ice_0.geometry} material={materials.material} position={[-25.157, 289.766, 25.192]} rotation={[-1.803, 0.216, 2.279]} scale={82.853} />
        <mesh geometry={nodes.Ice006_Ice_0.geometry} material={materials.material} position={[-36.949, 252.127, 16.478]} rotation={[-1.088, -0.184, -1.065]} scale={77.093} />
        <mesh geometry={nodes.Ice007_Ice_0.geometry} material={materials.material} position={[12.492, 248.297, 31.938]} rotation={[-1.423, -0.259, -2.616]} scale={91.001} />
        <mesh geometry={nodes.Ice008_Ice_0.geometry} material={materials.material} position={[-36.949, 253.304, -33.739]} rotation={[-1.088, -0.184, -1.065]} scale={77.093} />
        <mesh geometry={nodes.Ice009_Ice_0.geometry} material={materials.material} position={[7.95, 257.175, -9.154]} rotation={[-0.985, -0.601, -0.802]} scale={77.093} />
      </group>
    </group>
  )
}

useGLTF.preload('/ice_cream_soda.glb')
